/** Interactive wizard for creating and updating .env configuration. */

import chalk from 'chalk';
import boxen from 'boxen';
import inquirer from 'inquirer';
import dotenv from 'dotenv';
import { promises as fs } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';
import { visualHebrew } from '../../utils/rtl.js';

const PROJECT_ROOT = fileURLToPath(new URL('../../..', import.meta.url));
const ENV_PATH = path.join(PROJECT_ROOT, '.env');
const ENV_EXAMPLE_PATH = path.join(PROJECT_ROOT, '.env.example');
const ENV_BACKUP_PATH = path.join(PROJECT_ROOT, '.env.backup');

type EnvMap = Record<string, string>;

type DbMode = 'default' | 'sqlite-path' | 'postgres-url' | 'postgres-fields' | 'skip';

interface WizardOptions {
  dryRun?: boolean;
  force?: boolean;
}

// ─── helpers ──────────────────────────────────────────────────────────────────

function mask(value: string): string {
  if (!value) return chalk.gray('(empty)');
  return value.length <= 4
    ? '****'
    : `${value.slice(0, 2)}${'*'.repeat(value.length - 4)}${value.slice(-2)}`;
}

function sectionHeader(title: string): void {
  console.log('\n' + chalk.cyan.bold(`── ${title} ─────────────────────`));
}

async function readExampleDefaults(): Promise<EnvMap> {
  try {
    const raw = await fs.readFile(ENV_EXAMPLE_PATH, 'utf8');
    return dotenv.parse(raw);
  } catch {
    return {};
  }
}

async function readCurrentEnv(): Promise<EnvMap> {
  try {
    const raw = await fs.readFile(ENV_PATH, 'utf8');
    return dotenv.parse(raw);
  } catch {
    return {};
  }
}

function buildEnvContent(vars: EnvMap): string {
  const lines = [
    '# Generated by `fin setup env`',
    '',
    '# ─── Telegram Bot ──────────────────────────────────────────────────',
  ];

  if (vars.BOT_TOKEN !== undefined) lines.push(`BOT_TOKEN=${vars.BOT_TOKEN}`);
  if (vars.ALLOWED_TELEGRAM_IDS !== undefined)
    lines.push(`ALLOWED_TELEGRAM_IDS=${vars.ALLOWED_TELEGRAM_IDS}`);

  lines.push('', '# ─── Database ──────────────────────────────────────────────────────');

  if (vars.DATABASE_URL !== undefined) lines.push(`DATABASE_URL=${vars.DATABASE_URL}`);
  if (vars.DB_HOST !== undefined) lines.push(`DB_HOST=${vars.DB_HOST}`);
  if (vars.DB_PORT !== undefined) lines.push(`DB_PORT=${vars.DB_PORT}`);
  if (vars.DB_NAME !== undefined) lines.push(`DB_NAME=${vars.DB_NAME}`);
  if (vars.DB_USER !== undefined) lines.push(`DB_USER=${vars.DB_USER}`);
  if (vars.DB_PASSWORD !== undefined) lines.push(`DB_PASSWORD=${vars.DB_PASSWORD}`);
  if (vars.DB_SSL !== undefined) lines.push(`DB_SSL=${vars.DB_SSL}`);

  lines.push('', '# ─── App Config ────────────────────────────────────────────────────');
  if (vars.NODE_ENV !== undefined) lines.push(`NODE_ENV=${vars.NODE_ENV}`);

  // catch-all: any extra vars not explicitly placed above
  const knownKeys = new Set([
    'BOT_TOKEN',
    'ALLOWED_TELEGRAM_IDS',
    'DATABASE_URL',
    'DB_HOST',
    'DB_PORT',
    'DB_NAME',
    'DB_USER',
    'DB_PASSWORD',
    'DB_SSL',
    'NODE_ENV',
  ]);
  const extras = Object.entries(vars).filter(([k]) => !knownKeys.has(k));
  if (extras.length > 0) {
    lines.push('', '# ─── Other ──────────────────────────────────────────────────────────');
    extras.forEach(([k, v]) => lines.push(`${k}=${v}`));
  }

  return lines.join('\n') + '\n';
}

// ─── prompt sections ──────────────────────────────────────────────────────────

async function promptTelegram(current: EnvMap): Promise<Partial<EnvMap>> {
  sectionHeader(`Telegram Bot ${chalk.red(visualHebrew('(חובה)'))}`);
  console.log(chalk.gray(visualHebrew('BOT_TOKEN ו-ALLOWED_TELEGRAM_IDS נדרשים להפעלת הבוט.\n')));

  const { BOT_TOKEN } = await inquirer.prompt([
    {
      type: 'password',
      name: 'BOT_TOKEN',
      message: chalk.red('*') + ' BOT_TOKEN:',
      default: current.BOT_TOKEN ?? '',
      validate: (v: string) => v.trim().length > 0 || visualHebrew('BOT_TOKEN הוא שדה חובה'),
    },
  ]);

  const { ALLOWED_TELEGRAM_IDS } = await inquirer.prompt([
    {
      type: 'input',
      name: 'ALLOWED_TELEGRAM_IDS',
      message: chalk.red('*') + visualHebrew(' ALLOWED_TELEGRAM_IDS (מופרדים בפסיק):'),
      default: current.ALLOWED_TELEGRAM_IDS ?? '',
      validate: (v: string) =>
        /^\d+(\s*,\s*\d+)*$/.test(v.trim()) ||
        visualHebrew('הכנס מזהי טלגרם מספריים, מופרדים בפסיק'),
    },
  ]);

  const ids = (ALLOWED_TELEGRAM_IDS as string)
    .split(',')
    .map((s: string) => s.trim())
    .filter(Boolean);
  console.log(
    chalk.green(
      visualHebrew(`  ✓ ${ids.length} מזהה${ids.length !== 1 ? 'ים' : ''} יורשו: ${ids.join(', ')}`)
    )
  );

  return { BOT_TOKEN, ALLOWED_TELEGRAM_IDS };
}

async function promptDatabase(current: EnvMap): Promise<Partial<EnvMap>> {
  sectionHeader(`Database ${chalk.gray(visualHebrew('(אופציונלי)'))}`);
  console.log(
    chalk.gray(visualHebrew('ברירת מחדל: SQLite מוצפן ב-~/Library/Application Support/Asher/\n'))
  );

  const existingDbMode = (): DbMode => {
    if (current.DB_HOST) return 'postgres-fields';
    if (current.DATABASE_URL?.startsWith('sqlite')) return 'sqlite-path';
    if (current.DATABASE_URL?.startsWith('postgres')) return 'postgres-url';
    return 'default';
  };

  const { dbMode } = await inquirer.prompt([
    {
      type: 'list',
      name: 'dbMode',
      message: visualHebrew('הגדרת מסד נתונים:'),
      default: existingDbMode(),
      choices: [
        { name: visualHebrew('SQLite ברירת מחדל (מומלץ)'), value: 'default' },
        { name: visualHebrew('נתיב SQLite מותאם אישית'), value: 'sqlite-path' },
        { name: 'PostgreSQL — connection string (DATABASE_URL)', value: 'postgres-url' },
        { name: visualHebrew('PostgreSQL — שדות נפרדים'), value: 'postgres-fields' },
        { name: chalk.gray(visualHebrew('דלג לעת עתה')), value: 'skip' },
      ],
    },
  ]);

  if (dbMode === 'default' || dbMode === 'skip') return {};

  if (dbMode === 'sqlite-path') {
    const { DATABASE_URL } = await inquirer.prompt([
      {
        type: 'input',
        name: 'DATABASE_URL',
        message: visualHebrew('נתיב SQLite (לדוגמה: sqlite:///custom/path/db.sqlite):'),
        default: current.DATABASE_URL ?? 'sqlite:///',
        validate: (v: string) => v.trim().length > 0 || visualHebrew('הנתיב לא יכול להיות ריק'),
      },
    ]);
    return { DATABASE_URL };
  }

  if (dbMode === 'postgres-url') {
    const { DATABASE_URL } = await inquirer.prompt([
      {
        type: 'input',
        name: 'DATABASE_URL',
        message: 'PostgreSQL URL (postgres://user:pass@host:5432/db):',
        default: current.DATABASE_URL ?? 'postgres://',
        validate: (v: string) =>
          /^postgres(ql)?:\/\//.test(v.trim()) ||
          visualHebrew('חייב להתחיל ב-postgres:// או postgresql://'),
      },
    ]);
    return { DATABASE_URL };
  }

  // postgres-fields
  const answers = await inquirer.prompt([
    {
      type: 'input',
      name: 'DB_HOST',
      message: 'DB_HOST:',
      default: current.DB_HOST ?? 'localhost',
      validate: (v: string) => v.trim().length > 0 || visualHebrew('שדה חובה'),
    },
    {
      type: 'input',
      name: 'DB_PORT',
      message: 'DB_PORT:',
      default: current.DB_PORT ?? '5432',
      validate: (v: string) => {
        const n = parseInt(v, 10);
        return (n >= 1 && n <= 65535) || visualHebrew('חייב להיות בין 1 ל-65535');
      },
    },
    {
      type: 'input',
      name: 'DB_NAME',
      message: 'DB_NAME:',
      default: current.DB_NAME ?? 'bersaglio',
      validate: (v: string) => v.trim().length > 0 || visualHebrew('שדה חובה'),
    },
    {
      type: 'input',
      name: 'DB_USER',
      message: 'DB_USER:',
      default: current.DB_USER ?? 'postgres',
      validate: (v: string) => v.trim().length > 0 || visualHebrew('שדה חובה'),
    },
    {
      type: 'password',
      name: 'DB_PASSWORD',
      message: visualHebrew('DB_PASSWORD (השאר ריק אם אין):'),
      default: current.DB_PASSWORD ?? '',
    },
    {
      type: 'confirm',
      name: 'DB_SSL',
      message: visualHebrew('הפעל SSL?'),
      default: current.DB_SSL === 'true',
    },
  ]);

  return {
    DB_HOST: answers.DB_HOST,
    DB_PORT: answers.DB_PORT,
    DB_NAME: answers.DB_NAME,
    DB_USER: answers.DB_USER,
    DB_PASSWORD: answers.DB_PASSWORD,
    DB_SSL: String(answers.DB_SSL),
  };
}

async function promptAppConfig(current: EnvMap): Promise<Partial<EnvMap>> {
  sectionHeader(`App Config ${chalk.gray(visualHebrew('(אופציונלי)'))}`);

  const { NODE_ENV } = await inquirer.prompt([
    {
      type: 'list',
      name: 'NODE_ENV',
      message: visualHebrew('סביבת הרצה (NODE_ENV):'),
      default: current.NODE_ENV ?? 'development',
      choices: ['development', 'production', 'test'],
    },
  ]);

  return { NODE_ENV };
}

// ─── catch-all for unknown .env.example vars ──────────────────────────────────

async function promptUnknownVars(
  exampleDefaults: EnvMap,
  current: EnvMap,
  collected: EnvMap
): Promise<Partial<EnvMap>> {
  const knownKeys = new Set([
    'BOT_TOKEN',
    'ALLOWED_TELEGRAM_IDS',
    'DATABASE_URL',
    'DB_HOST',
    'DB_PORT',
    'DB_NAME',
    'DB_USER',
    'DB_PASSWORD',
    'DB_SSL',
    'NODE_ENV',
  ]);

  const unknownKeys = Object.keys(exampleDefaults).filter(k => !knownKeys.has(k));
  if (unknownKeys.length === 0) return {};

  sectionHeader(visualHebrew('משתנים נוספים'));
  const result: Partial<EnvMap> = {};

  for (const key of unknownKeys) {
    if (collected[key] !== undefined) continue;
    const { value } = await inquirer.prompt([
      {
        type: 'input',
        name: 'value',
        message: `${key}:`,
        default: current[key] ?? exampleDefaults[key] ?? '',
      },
    ]);
    result[key] = value;
  }

  return result;
}

// ─── summary ─────────────────────────────────────────────────────────────────

function printSummary(vars: EnvMap): void {
  const sensitiveKeys = new Set(['BOT_TOKEN', 'DB_PASSWORD']);
  const lines = Object.entries(vars)
    .filter(([, v]) => v !== '')
    .map(([k, v]) => `  ${chalk.bold(k)} = ${sensitiveKeys.has(k) ? mask(v) : chalk.green(v)}`);

  console.log(
    '\n' +
      boxen(lines.join('\n'), {
        title: chalk.bold(visualHebrew('סיכום')),
        padding: 1,
        borderColor: 'cyan',
        borderStyle: 'round',
      })
  );
}

// ─── update mode menu ─────────────────────────────────────────────────────────

type UpdateChoice = 'specific' | 'all' | 'verify';

async function promptUpdateMode(): Promise<UpdateChoice> {
  const { choice } = await inquirer.prompt([
    {
      type: 'list',
      name: 'choice',
      message: visualHebrew('קובץ .env קיים. מה תרצה לעשות?'),
      choices: [
        { name: visualHebrew('עדכן משתנים ספציפיים'), value: 'specific' },
        { name: visualHebrew('הרץ אשף מלא (עדכן הכל)'), value: 'all' },
        { name: visualHebrew('הצג ערכים נוכחיים (קריאה בלבד)'), value: 'verify' },
      ],
    },
  ]);
  return choice;
}

async function promptSelectVarsToUpdate(current: EnvMap): Promise<string[]> {
  const choices = Object.keys(current).map(k => ({ name: k, value: k, checked: false }));
  const { selected } = await inquirer.prompt([
    {
      type: 'checkbox',
      name: 'selected',
      message: visualHebrew('בחר משתנים לעדכון:'),
      choices,
    },
  ]);
  return selected;
}

// ─── main ─────────────────────────────────────────────────────────────────────

export async function runEnvWizard(options: WizardOptions = {}): Promise<void> {
  const { dryRun = false, force = false } = options;

  console.log(
    '\n' +
      boxen(chalk.bold(visualHebrew('Bersaglio — אשף הגדרת .env')), {
        padding: 1,
        borderColor: 'cyan',
        borderStyle: 'round',
      })
  );

  if (dryRun) console.log(chalk.yellow(visualHebrew('\n  [dry-run] לא יישמר כלום לדיסק.\n')));

  const exampleDefaults = await readExampleDefaults();
  const envExists = await fs
    .access(ENV_PATH)
    .then(() => true)
    .catch(() => false);
  const current: EnvMap = envExists ? await readCurrentEnv() : {};

  // ── force mode (CI) ──────────────────────────────────────────────────────
  if (force) {
    const vars: EnvMap = { ...exampleDefaults, ...current };
    printSummary(vars);
    if (!dryRun) {
      if (envExists) await fs.copyFile(ENV_PATH, ENV_BACKUP_PATH);
      await fs.writeFile(ENV_PATH, buildEnvContent(vars), 'utf8');
      console.log(
        chalk.green(
          visualHebrew('\n✅  .env נכתב (מצב force — ערכים קיימים + ברירות מחדל מ-.env.example)')
        )
      );
      if (envExists) console.log(chalk.gray(visualHebrew('   גיבוי נשמר ב-.env.backup')));
    }
    return;
  }

  // ── update mode ───────────────────────────────────────────────────────────
  if (envExists) {
    const updateChoice = await promptUpdateMode();

    if (updateChoice === 'verify') {
      printSummary(current);
      return;
    }

    if (updateChoice === 'specific') {
      const keysToUpdate = await promptSelectVarsToUpdate(current);
      if (keysToUpdate.length === 0) {
        console.log(chalk.gray(visualHebrew('\nלא נבחרו משתנים. לא בוצע שינוי.')));
        return;
      }

      let updated: Partial<EnvMap> = {};

      // Prompt only selected keys, one at a time
      for (const key of keysToUpdate) {
        const sensitiveKeys = new Set(['BOT_TOKEN', 'DB_PASSWORD']);
        const { value } = await inquirer.prompt([
          {
            type: sensitiveKeys.has(key) ? 'password' : 'input',
            name: 'value',
            message: `${key}:`,
            default: current[key] ?? '',
          },
        ]);
        updated[key] = value;
      }

      const merged: EnvMap = {
        ...current,
        ...(Object.fromEntries(
          Object.entries(updated).filter(([, v]) => v !== undefined)
        ) as EnvMap),
      };
      printSummary(merged);

      const { confirm } = await inquirer.prompt([
        {
          type: 'confirm',
          name: 'confirm',
          message: visualHebrew('לכתוב ערכים אלה ל-.env?'),
          default: true,
        },
      ]);
      if (!confirm) {
        console.log(chalk.gray(visualHebrew('בוטל.')));
        return;
      }

      if (!dryRun) {
        await fs.copyFile(ENV_PATH, ENV_BACKUP_PATH);
        await fs.writeFile(ENV_PATH, buildEnvContent(merged), 'utf8');
        console.log(chalk.green(visualHebrew('\n✅  .env עודכן.')));
        console.log(chalk.gray(visualHebrew('   גיבוי נשמר ב-.env.backup')));
      }
      return;
    }
    // fall through to full wizard (updateChoice === 'all')
  }

  // ── full wizard (create or update-all) ───────────────────────────────────
  const telegramVars = await promptTelegram(current);
  const dbVars = await promptDatabase(current);
  const appVars = await promptAppConfig(current);

  const collected: EnvMap = {
    ...telegramVars,
    ...dbVars,
    ...appVars,
  } as EnvMap;

  const unknownVars = await promptUnknownVars(exampleDefaults, current, collected);
  const allVars: EnvMap = { ...collected, ...unknownVars } as EnvMap;

  printSummary(allVars);

  const { confirm } = await inquirer.prompt([
    {
      type: 'confirm',
      name: 'confirm',
      message: visualHebrew('לכתוב ערכים אלה ל-.env?'),
      default: true,
    },
  ]);

  if (!confirm) {
    console.log(chalk.gray(visualHebrew('בוטל.')));
    return;
  }

  if (!dryRun) {
    if (envExists) await fs.copyFile(ENV_PATH, ENV_BACKUP_PATH);
    await fs.writeFile(ENV_PATH, buildEnvContent(allVars), 'utf8');
    console.log(chalk.green(visualHebrew('\n✅  .env נכתב בהצלחה.')));
    if (envExists) console.log(chalk.gray(visualHebrew('   .env הקודם גובה ב-.env.backup')));
    console.log(chalk.gray(visualHebrew('\nצעדים הבאים:')));
    console.log(chalk.gray(visualHebrew('  fin setup db      — אתחל מסד נתונים')));
    console.log(chalk.gray(visualHebrew('  fin setup creds   — ייבא פרטי גישה לבנקים')));
    console.log(chalk.gray(visualHebrew('  fin start all     — הפעל את כל השירותים')));
  } else {
    console.log(chalk.yellow(visualHebrew('\n[dry-run] היה נכתב ל-.env:')));
  }
}
